@ECHO OFF
REM --- CONFIGURACION ---
SET DB_USER=fort
SET DB_PASSWORD=nvdp1 
SET DB_SID=XEPDB1
SET DB_DIRECTORY=NVDPA_BACKUP_DIR

REM --- NOMBRE DEL ARCHIVO ---
SET FECHA=%date:~10,4%-%date:~4,2%-%date:~7,2%
SET FILENAME=NVDPA_AUTO_BKP_%FECHA%.dmp
SET LOGFILENAME=NVDPA_AUTO_BKP_%FECHA%.log

REM --- COMANDO DE EXPORTACION ---
expdp %DB_USER%/%DB_PASSWORD%@%DB_SID% SCHEMAS=%DB_USER% DIRECTORY=%DB_DIRECTORY% DUMPFILE=%FILENAME% LOGFILE=%LOGFILENAME%